### list users
GET http://localhost:3000/coffees
Content-Type: application/json

### list users
GET http://localhost:3000/coffees?offset=2&limit=2
Content-Type: application/json
### list user
GET http://localhost:3000/coffees/3
Content-Type: application/json
### nuevo
POST http://localhost:3000/coffees
Content-Type: application/json

  {
    "name": "gordo chato 3",
    "brand": "pollos copacabana",
    "flavors": [
      "gato",
      "perro"
    ]
  }
###
PATCH http://localhost:3000/coffees/3
Content-Type: application/json

{
    "name": "ahora sin llawja"
}
###
DELETE http://localhost:3000/coffees/2
Content-Type: application/json