### list users
GET http://localhost:3000/coffees
Content-Type: application/json
### list user
GET http://localhost:3000/coffees/3
Content-Type: application/json
### nuevo
POST http://localhost:3000/coffees
Content-Type: application/json

  {
    "name": "api con llajwa",
    "brand": "copacabana",
    "flavors": [
      "manzanilla",
      "narnaja"
    ]
  }
###
PATCH http://localhost:3000/coffees/3
Content-Type: application/json

{
    "name": "lauraaa"
}
###
DELETE http://localhost:3000/coffees/2
Content-Type: application/json